### PR TITLE
Backup target table when replacing, only deleting when renaming succeeds

### PR DESCRIPTION
**Pull request by wemrysi**
To guard against losing the previous data if renaming fails for some reason.

### CODE REVIEW

**Review by cryogenian — APPROVED** [review]
:+1:

**Comment by rintcius** [comment]
@wemrysi Could you push this to `precog` org instead? I think that's the reason the build is failing.

**Comment by wemrysi** [comment]
> @wemrysi Could you push this to `precog` org instead? I think that's the reason the build is failing.

🤦 thanks for noticing @rintcius!

**Comment by wemrysi** [comment]
Closing in favor of #270.

**Pull request closed without merging**
